apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web
  namespace: demo
  labels:
    app: python-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web
  strategy: {}
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-web
        image: 178076403251.dkr.ecr.us-east-2.amazonaws.com/fargate-poc:1
        ports:
          - containerPort: 8080
        resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: python-web
  namespace: demo
spec:
  selector:
    app: python-web
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: python-web
  namespace: demo
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /
            backend:
              serviceName: python-web
              servicePort: 80
